### ISSUE TITLE
Network Clustering doesn't cluster correctly

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#124]
##### Network version

1.4.2

##### Orange version

3.23.dev

##### Expected behavior
Network Clustering clusters the data correctly, i.e. reported number of clusters found and the actual number of clusters in the data are the same.

##### Actual behavior
Regardless of the method chosen, the clustering is always the same. It doesn't match the reported number of clusters (widget says 162 clusters found, data reports 93). Also, the clustering doesn't change regardless of the method chosen.

##### Steps to reproduce the behavior
Network File (lastfm) - Network Clustering. Change the method a couple of times and observe the output. Cluster values are not correct.

##### Additional info (worksheets, data, screenshots, ...)
<img width="647" alt="Screen Shot 2019-08-21 at 12 19 32" src="https://user-images.githubusercontent.com/12524972/63424126-0db40a80-c40e-11e9-99fd-8a5a32d9e57e.png">

**Comment by matejklemen** [comment]
If I understood correctly, "data reports 93 clusters" in this example means that upon sorting `Cluster` in descending order, `C93` is on top?  

If so, I think this might just be a misunderstanding. The values of `Cluster` variable are not padded to a fixed number of digits, so the string sorting produces a non-intuitive sorting. For example, if we have clusters `['C99', 'C100']` and try to sort them in descending order, we get `['C99', 'C100']` instead of the intuitive descending ordering `['C100', 'C99']`.  

What I'm trying to say is that I think "C154" is present somewhere in the table, it's just not presented correctly in the table (at the top).

Could you please check if this is indeed the case. Thanks :slightly_smiling_face:  
(in this case, all that needs to be changed is to pad cluster IDs to a fixed number of digits, e.g. name clusters `['C099', 'C100']` in the above example)

**Comment by ajdapretnar** [comment]
@matejklemen No, this is not the case. I simply didn't know how to show the issue. If you look for the highest number of reported clusters (or N-1 in case index starts at 0), there is no such cluster for the second method.

Also, clustering should be reproducible. Set the random seed to 0 as in other Orange widgets.

**Comment by ajdapretnar** [comment]
By the way, clustering simply never gets updated. It stays the same as with the first run.

**Comment by matejklemen** [comment]
I'm afraid I still can't reproduce the issue :confused: 
I've added an option to do reproducible clustering locally (i.e. set seed to 0) and tried it a few times, it gives consistent results across multiple runs (in my case, 149 clusters) and I can find "C149" in the data table. Seems to work properly when not using seed as well.  

I noticed something unusual though, the results from each new clustering run show up in data table as an additional feature, e.g. if I run clustering three times, there will be three new attributes in the table (`Cluster`, `Cluster(1)`, `Cluster(2)`), each containing clusters for their run.  
I wanted to ask you, is this useful for some common use case? It would seem more intuitive to me that each `Network Clustering` widget would only output one feature and keep overriding that one if the method was changed.

**Comment by ajdapretnar** [comment]
> the results from each new clustering run show up in data table as an additional feature

Right! That's what confused me! I was always looking at Cluster feature, so I just thought it never gets updated. But you are right, new clusters are added as new features.

Yes, it should override as in other Orange widgets.
