### ISSUE TITLE
Directed Network: have a nicer self-directed visualization

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#174]
##### Network version

1.5.1

##### Orange version

3.28.dev

##### Expected behavior
Self-directed nodes have a clear return loop.
![K9Dz3](https://user-images.githubusercontent.com/12524972/97007771-353ac180-1542-11eb-84cc-c91643c0af65.png)

##### Actual behavior
What that?
<img width="420" alt="Screen Shot 2020-10-23 at 14 47 48" src="https://user-images.githubusercontent.com/12524972/97007710-19372000-1542-11eb-8a32-79f6372a2e7d.png">

##### Steps to reproduce the behavior
[CIRC.NET.zip](https://github.com/biolab/orange3-network/files/5429655/CIRC.NET.zip)

**Comment by janezd** [comment]
I don't really know what to do with them.

Here it looks kind of OK (I haven't drawn an arrow because it would be a mild pain in the neck):

<img width="286" alt="Screenshot 2021-01-28 at 16 18 26" src="https://user-images.githubusercontent.com/2387315/106159145-c8f4dd00-6184-11eb-83ce-cfbfd0fe67d6.png">

Here, the point with the loop is on the right side and other edges cross the loop. It would seem obvious that the loop can be draw to the right of the vertex, but this situation is difficult to detect.

<img width="193" alt="Screenshot 2021-01-28 at 16 19 10" src="https://user-images.githubusercontent.com/2387315/106159363-fd689900-6184-11eb-8e12-d796d9f05218.png">

This data actually has weights on edges. If we draw weighted edges, we get

<img width="205" alt="Screenshot 2021-01-28 at 16 19 24" src="https://user-images.githubusercontent.com/2387315/106159408-0b1e1e80-6185-11eb-8701-1e2b94482510.png">

I can simply add this code and let's say it's better than before... Mind you, this visualization isn't only incapable of drawing loops but also can't draw multiple edges between pairs of points. It works properly only on simple graphs.

**Comment by ajdapretnar** [comment]
I'm sorry, I don't think this works well. :(

1. With directed edges there is inconsistency in arrows. Some lines go to the end of the triangle, others don't. Is that intentional? It is not major, just something I have noticed.
<img width="151" alt="Screen Shot 2021-01-29 at 10 38 10" src="https://user-images.githubusercontent.com/12524972/106258555-44569d00-621e-11eb-8495-a07934e349b5.png">

2. A major issue is with drawing the edges in undirected zoomed out networks, such as lastfm. This, to me, is quite horrible. It looks good once zoomed in, but the first image is wild. Edges are not touching nodes as they should, some overlap nodes, etc.
<img width="942" alt="Screen Shot 2021-01-29 at 10 38 48" src="https://user-images.githubusercontent.com/12524972/106258720-81229400-621e-11eb-8656-427159b1e29e.png">

**Comment by janezd** [comment]
1. No, they all end before the arrow. What you are seeing are two lines going into opposite directions. I have already noticed this, but decided to leave it, for two reasons. One is that it adds information: it tells you that this edge is bidirectional even though you're only looking at one side. The other is that not drawing it like this would be require checking whether there is an arrow going in the opposite direction. This cannot be done efficiently with the data structure that is currently used for plotting.

2a. I can (and probably should) make the edges touch the vertices in overcrowded plots like this one.

2b. Overlaping? Do you mean the artefacts at the bottom right? This happens because two connected vertices are ovelapping; when going a few pixels away from vertices, the edge is drawn essentially backwards (though the arrow would still have the correct direction). I could fix this, but then I don't know what to actually draw. There are two artefacts there -- the more vertical edges at the bottom, which are kind of OK, and the horizontal-ish one, which is weirder, but I don't know what to replace it with. Any suggestions how to draw this?

**Comment by ajdapretnar** [comment]
1. Right. This is very subtle. I like it, but I doubt anyone will notice it? 🤔 It doesn't bother though, so we can leave it.
2a. Yes, edges should touch. Always, IMO.
2b. It was nicer before. I would keep it as is.
